// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package com_ta04_srv_payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Payment is a message for payment
type Payment struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              int32    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payment) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Payment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Payment) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// IndexPaymentRequest is a message for IndexPayments
type IndexPaymentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexPaymentsRequest) Reset()         { *m = IndexPaymentsRequest{} }
func (m *IndexPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*IndexPaymentsRequest) ProtoMessage()    {}
func (*IndexPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *IndexPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPaymentsRequest.Unmarshal(m, b)
}
func (m *IndexPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPaymentsRequest.Marshal(b, m, deterministic)
}
func (m *IndexPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPaymentsRequest.Merge(m, src)
}
func (m *IndexPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_IndexPaymentsRequest.Size(m)
}
func (m *IndexPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPaymentsRequest proto.InternalMessageInfo

// Response is a response message
type Response struct {
	Payment              *Payment   `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payments             []*Payment `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

// Error is an error message
type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "com.ta04.srv.payment.Payment")
	proto.RegisterType((*IndexPaymentsRequest)(nil), "com.ta04.srv.payment.IndexPaymentsRequest")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.payment.Response")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.payment.Error")
}

func init() {
	proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410)
}

var fileDescriptor_6362648dfa63d410 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x2d, 0x05, 0x5a, 0x06, 0xe1, 0x30, 0x21, 0xa4, 0x6a, 0x34, 0x4d, 0x4f, 0xc4, 0xc3,
	0x46, 0x51, 0x63, 0xbc, 0xeb, 0x81, 0x8b, 0xe2, 0x12, 0x8f, 0x46, 0x2b, 0x3b, 0xd1, 0x1e, 0x60,
	0xeb, 0xee, 0x82, 0xf2, 0xb3, 0x3c, 0xf8, 0xff, 0x0c, 0xcb, 0xd6, 0xc4, 0xa4, 0x51, 0x0f, 0xbd,
	0xcd, 0x4c, 0x5f, 0xdf, 0x7c, 0xfb, 0x36, 0x0b, 0x9d, 0x3c, 0x5d, 0xcd, 0x68, 0x6e, 0x58, 0xae,
	0xa4, 0x91, 0xd8, 0x9b, 0xca, 0x19, 0x33, 0xe9, 0xd1, 0x29, 0xd3, 0x6a, 0xc9, 0xdc, 0xb7, 0xe4,
	0x11, 0x82, 0xf1, 0xa6, 0xc4, 0x2e, 0xd4, 0x32, 0x11, 0x79, 0xb1, 0x37, 0x68, 0xf0, 0x5a, 0x26,
	0x70, 0x07, 0x42, 0xa9, 0x04, 0xa9, 0x87, 0x4c, 0x44, 0x35, 0x3b, 0x0d, 0x6c, 0x3f, 0x12, 0x88,
	0x50, 0x37, 0xab, 0x9c, 0x22, 0x3f, 0xf6, 0x06, 0x2d, 0x6e, 0x6b, 0xec, 0x43, 0x53, 0x9b, 0xd4,
	0x2c, 0x74, 0x54, 0x8f, 0xbd, 0x41, 0xc8, 0x5d, 0x97, 0xf4, 0xa1, 0x37, 0x9a, 0x0b, 0x7a, 0x77,
	0x6b, 0x34, 0xa7, 0xd7, 0x05, 0x69, 0x93, 0x7c, 0x78, 0x10, 0x72, 0xd2, 0xb9, 0x9c, 0x6b, 0xc2,
	0x73, 0x08, 0x1c, 0x91, 0x05, 0x68, 0x0f, 0xf7, 0x59, 0x19, 0x2e, 0x73, 0x26, 0xbc, 0x50, 0xe3,
	0x31, 0x34, 0x48, 0x29, 0xa9, 0x2c, 0x61, 0x7b, 0xb8, 0x57, 0xfe, 0xdb, 0xd5, 0x5a, 0xc2, 0x37,
	0x4a, 0xbc, 0x80, 0xd0, 0xcd, 0x75, 0xe4, 0xc7, 0xfe, 0xdf, 0xcb, 0xbe, 0xe5, 0xc9, 0x19, 0x34,
	0xac, 0xd5, 0x3a, 0x80, 0xa9, 0x14, 0x64, 0x61, 0x5b, 0xdc, 0xd6, 0x18, 0x41, 0x30, 0x23, 0xad,
	0xd3, 0x67, 0xb2, 0x30, 0x2d, 0x5e, 0xb4, 0xc3, 0x4f, 0x1f, 0xba, 0xce, 0x6c, 0x42, 0x6a, 0x99,
	0x4d, 0x09, 0xef, 0xa1, 0xf3, 0x23, 0x15, 0x3c, 0x2c, 0x67, 0x28, 0x8b, 0x6e, 0xf7, 0xa0, 0x5c,
	0x5b, 0xa4, 0x99, 0x6c, 0xe1, 0x35, 0xb4, 0x27, 0x2f, 0xf2, 0xad, 0xb8, 0xda, 0xdf, 0x0f, 0xf8,
	0x0f, 0xbf, 0x1b, 0xd8, 0x9e, 0x18, 0xa9, 0xa8, 0x32, 0xc3, 0x31, 0x74, 0xee, 0x72, 0x91, 0x9a,
	0xea, 0x1c, 0x6f, 0xa1, 0x7b, 0x49, 0xda, 0x28, 0xb9, 0xaa, 0xca, 0xf2, 0xa9, 0x69, 0x5f, 0xce,
	0xc9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x99, 0xfa, 0xcd, 0x4a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PaymentService service

type PaymentServiceClient interface {
	// IndexPayments is a method to index all payments
	IndexPayments(ctx context.Context, in *IndexPaymentsRequest, opts ...client.CallOption) (*Response, error)
	// ShowPayment is a method to show a payment
	ShowPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
	// StorePayment is a method to store a new payment
	StorePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
	// UpdatePayment is a method to update a payment
	UpdatePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
	// DestroyPayment is a method to delete a payment
	DestroyPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
}

type paymentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPaymentServiceClient(serviceName string, c client.Client) PaymentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.ta04.srv.payment"
	}
	return &paymentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *paymentServiceClient) IndexPayments(ctx context.Context, in *IndexPaymentsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.IndexPayments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ShowPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.ShowPayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StorePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.StorePayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) UpdatePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.UpdatePayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) DestroyPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.DestroyPayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceHandler interface {
	// IndexPayments is a method to index all payments
	IndexPayments(context.Context, *IndexPaymentsRequest, *Response) error
	// ShowPayment is a method to show a payment
	ShowPayment(context.Context, *Payment, *Response) error
	// StorePayment is a method to store a new payment
	StorePayment(context.Context, *Payment, *Response) error
	// UpdatePayment is a method to update a payment
	UpdatePayment(context.Context, *Payment, *Response) error
	// DestroyPayment is a method to delete a payment
	DestroyPayment(context.Context, *Payment, *Response) error
}

func RegisterPaymentServiceHandler(s server.Server, hdlr PaymentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PaymentService{hdlr}, opts...))
}

type PaymentService struct {
	PaymentServiceHandler
}

func (h *PaymentService) IndexPayments(ctx context.Context, in *IndexPaymentsRequest, out *Response) error {
	return h.PaymentServiceHandler.IndexPayments(ctx, in, out)
}

func (h *PaymentService) ShowPayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.ShowPayment(ctx, in, out)
}

func (h *PaymentService) StorePayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.StorePayment(ctx, in, out)
}

func (h *PaymentService) UpdatePayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.UpdatePayment(ctx, in, out)
}

func (h *PaymentService) DestroyPayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.DestroyPayment(ctx, in, out)
}
