// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package com_ta04_srv_payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              int32    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethodId      int32    `protobuf:"varint,3,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payment) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Payment) GetPaymentMethodId() int32 {
	if m != nil {
		return m.PaymentMethodId
	}
	return 0
}

func (m *Payment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Order struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            int32    `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Order) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type IndexPaymentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexPaymentsRequest) Reset()         { *m = IndexPaymentsRequest{} }
func (m *IndexPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*IndexPaymentsRequest) ProtoMessage()    {}
func (*IndexPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *IndexPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPaymentsRequest.Unmarshal(m, b)
}
func (m *IndexPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPaymentsRequest.Marshal(b, m, deterministic)
}
func (m *IndexPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPaymentsRequest.Merge(m, src)
}
func (m *IndexPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_IndexPaymentsRequest.Size(m)
}
func (m *IndexPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPaymentsRequest proto.InternalMessageInfo

type Response struct {
	Payment              *Payment   `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payments             []*Payment `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Payment)(nil), "com.ta04.srv.payment.Payment")
	proto.RegisterType((*Order)(nil), "com.ta04.srv.payment.Order")
	proto.RegisterType((*IndexPaymentsRequest)(nil), "com.ta04.srv.payment.IndexPaymentsRequest")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.payment.Response")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.payment.Error")
}

func init() {
	proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410)
}

var fileDescriptor_6362648dfa63d410 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0xaf, 0xd2, 0x40,
	0x10, 0xc6, 0x2d, 0xa5, 0x94, 0x0e, 0x82, 0x71, 0x42, 0xb0, 0x6a, 0x30, 0xa4, 0x27, 0xc2, 0xa1,
	0x51, 0xd4, 0x18, 0xaf, 0x46, 0x0f, 0x3d, 0x28, 0x64, 0x09, 0x47, 0x43, 0x6a, 0x77, 0x03, 0x3d,
	0x94, 0xad, 0xbb, 0x5b, 0x84, 0x3f, 0xcb, 0xa3, 0xff, 0x9d, 0xe9, 0x76, 0xab, 0xef, 0xe5, 0xf5,
	0xf1, 0x38, 0x70, 0xdb, 0x99, 0xf9, 0xfa, 0x9b, 0x6f, 0xbf, 0x6c, 0xa1, 0x9f, 0xc7, 0xa7, 0x8c,
	0xed, 0x55, 0x98, 0x0b, 0xae, 0x38, 0x0e, 0x13, 0x9e, 0x85, 0x2a, 0x7e, 0xfd, 0x2e, 0x94, 0xe2,
	0x10, 0x9a, 0x59, 0x70, 0x04, 0x77, 0x59, 0x1d, 0x71, 0x00, 0xad, 0x94, 0xfa, 0xd6, 0xc4, 0x9a,
	0x3a, 0xa4, 0x95, 0x52, 0x7c, 0x0e, 0x5d, 0x2e, 0x28, 0x13, 0x9b, 0x94, 0xfa, 0x2d, 0xdd, 0x75,
	0x75, 0x1d, 0x51, 0x9c, 0xc1, 0x53, 0x03, 0xd8, 0x64, 0x4c, 0xed, 0x38, 0x2d, 0x35, 0xb6, 0xd6,
	0x3c, 0x31, 0x83, 0xaf, 0xba, 0x1f, 0x51, 0x1c, 0x41, 0x47, 0xaa, 0x58, 0x15, 0xd2, 0x6f, 0x4f,
	0xac, 0xa9, 0x47, 0x4c, 0x15, 0x6c, 0xc1, 0x59, 0x94, 0xb8, 0x3b, 0x7b, 0xc7, 0x00, 0xb9, 0xe0,
	0xb4, 0x48, 0xd4, 0xff, 0xcd, 0x9e, 0xe9, 0x44, 0x14, 0x9f, 0x81, 0x5b, 0xc8, 0xca, 0x55, 0xb5,
	0xb1, 0x53, 0x96, 0x67, 0x16, 0x8d, 0x60, 0x18, 0xed, 0x29, 0x3b, 0x9a, 0x7b, 0x4a, 0xc2, 0x7e,
	0x16, 0x4c, 0xaa, 0xe0, 0xb7, 0x05, 0x5d, 0xc2, 0x64, 0xce, 0xf7, 0x92, 0xe1, 0x07, 0x70, 0x8d,
	0x71, 0xed, 0xa4, 0x37, 0x1f, 0x87, 0x4d, 0x79, 0x85, 0x06, 0x42, 0x6a, 0x35, 0xbe, 0x01, 0x87,
	0x09, 0xc1, 0x85, 0x36, 0xda, 0x9b, 0xbf, 0x6c, 0xfe, 0xec, 0x4b, 0x29, 0x21, 0x95, 0x12, 0x3f,
	0x42, 0xd7, 0xf4, 0xa5, 0x6f, 0x4f, 0xec, 0x87, 0x97, 0xfd, 0x93, 0x07, 0xef, 0xc1, 0xd1, 0x28,
	0x44, 0x68, 0x27, 0x9c, 0x32, 0x6d, 0xd6, 0x23, 0xfa, 0x8c, 0x3e, 0xb8, 0x19, 0x93, 0x32, 0xde,
	0x32, 0x6d, 0xc6, 0x23, 0x75, 0x39, 0xff, 0x63, 0xc3, 0xc0, 0xc0, 0x56, 0x4c, 0x1c, 0xd2, 0x84,
	0xe1, 0x77, 0xe8, 0xdf, 0x4a, 0x05, 0x67, 0xcd, 0x1e, 0x9a, 0xa2, 0x7b, 0xf1, 0xaa, 0x59, 0x5b,
	0xa7, 0x19, 0x3c, 0xc2, 0x6f, 0xd0, 0x5b, 0xed, 0xf8, 0xaf, 0xfa, 0x6d, 0x9d, 0xbf, 0xe0, 0x05,
	0xbc, 0x35, 0x0c, 0x6f, 0xf0, 0x3e, 0x9d, 0xf4, 0xd3, 0x89, 0x3e, 0xe3, 0x3d, 0x79, 0xeb, 0xf1,
	0x05, 0xd8, 0x05, 0x3c, 0x5e, 0x29, 0x2e, 0xd8, 0xd5, 0x7c, 0x2e, 0xa1, 0xbf, 0xce, 0x69, 0xac,
	0xae, 0x46, 0xfc, 0xd1, 0xd1, 0xbf, 0xef, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x0b,
	0x0a, 0x8b, 0xcf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PaymentService service

type PaymentServiceClient interface {
	IndexPayments(ctx context.Context, in *IndexPaymentsRequest, opts ...client.CallOption) (*Response, error)
	ShowPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
	ShowPaymentByOrderID(ctx context.Context, in *Order, opts ...client.CallOption) (*Response, error)
	StorePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
	UpdatePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error)
}

type paymentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPaymentServiceClient(serviceName string, c client.Client) PaymentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.ta04.srv.payment"
	}
	return &paymentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *paymentServiceClient) IndexPayments(ctx context.Context, in *IndexPaymentsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.IndexPayments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ShowPayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.ShowPayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ShowPaymentByOrderID(ctx context.Context, in *Order, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.ShowPaymentByOrderID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) StorePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.StorePayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) UpdatePayment(ctx context.Context, in *Payment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.UpdatePayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceHandler interface {
	IndexPayments(context.Context, *IndexPaymentsRequest, *Response) error
	ShowPayment(context.Context, *Payment, *Response) error
	ShowPaymentByOrderID(context.Context, *Order, *Response) error
	StorePayment(context.Context, *Payment, *Response) error
	UpdatePayment(context.Context, *Payment, *Response) error
}

func RegisterPaymentServiceHandler(s server.Server, hdlr PaymentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PaymentService{hdlr}, opts...))
}

type PaymentService struct {
	PaymentServiceHandler
}

func (h *PaymentService) IndexPayments(ctx context.Context, in *IndexPaymentsRequest, out *Response) error {
	return h.PaymentServiceHandler.IndexPayments(ctx, in, out)
}

func (h *PaymentService) ShowPayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.ShowPayment(ctx, in, out)
}

func (h *PaymentService) ShowPaymentByOrderID(ctx context.Context, in *Order, out *Response) error {
	return h.PaymentServiceHandler.ShowPaymentByOrderID(ctx, in, out)
}

func (h *PaymentService) StorePayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.StorePayment(ctx, in, out)
}

func (h *PaymentService) UpdatePayment(ctx context.Context, in *Payment, out *Response) error {
	return h.PaymentServiceHandler.UpdatePayment(ctx, in, out)
}
